### ISSUE TITLE
When are you gonna add Pellet Mode? /QUESTION/

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#62] opened 2016-11-19 04:11 UTC
When?

**Comment by Tyler3D** [comment] 2016-11-19 04:19
Duplicate of #8 #43 #45 And a bunch more

> Alright, since people are requesting it I guess I could start working on it, but I'm very busy right now. Still have a lot of features and bugs to fix so it might not be for a while until its implemented.

**Comment by Tyler3D** [comment] 2016-11-19 04:19
@NameYT

**Closed** 2016-11-19 04:43 UTC
