### ISSUE TITLE
Multisplitting in agar.io

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#761] opened 2017-04-14 16:38 UTC
in agar.io even with retina graphics, i not have lag when i split fast , nevertheless with MO-E , when i split fast i have lag , why? I also use protocol 6 and with low graphics

**Comment by Luka967** [comment] 2017-04-14 18:01
Duplicate of #760

**Comment by FantasyIsBae** [comment] 2017-04-14 18:12
I answered your question already @gyeyoqu  stop duplicating issues for no reason.

**Comment by FantasyIsBae** [comment] 2017-04-14 18:12
Close this.

**Comment by MastaCoder** [comment] 2017-04-14 18:35
Stop posting issues, just stop.

**Closed by MastaCoder** 2017-04-14 18:35 UTC
