### ISSUE TITLE
Auto restart for self feed?

### ISSUE THREAD

**Issue by Osher12** [Megabyte918/MultiOgar-Edited#458] opened 2017-01-27 17:12 UTC
hello, can someone help me with auto restart for self feed :) like ugar.pw

**Comment by AlexHGaming** [comment] 2017-01-27 18:11
I don't understand what you mean
Feeding your cell, counts as it's thinking you've fed another cell
I don't understand [x2] why you would even want an option like this.

**Comment by Megabyte918** [comment] 2017-01-28 00:14
Duplicate of #266;

**Closed by Megabyte918** 2017-01-28 00:14 UTC
