### ISSUE TITLE
Players cant see each other's skins

### ISSUE THREAD

**Issue by ARBCells** [Megabyte918/MultiOgar-Edited#556] opened 2017-02-16 01:24 UTC
When I run MultiOgar-Edited the players can not see each other's skins, but they can only see their own. This does not happen if I run MultiOgar from Barbosik, such as ''Raga'' does.

So, this issue can not be client-sided... I'm talking of course about using the Agar.io client.

**Comment by Megabyte918** [comment] 2017-02-16 01:47
Duplicate of #61, #65, #241, #249, #360, and #430. I will say again, nothing in this fork of MultiOgar has edited anything regarding skin usage, only thing regarding skins is randomskins and a custom skins script. 

Miniclip has unfortunately patched skins on the agario client, therefore the bug you are describing happens on both MultiOgar Edited and the original MultiOgar. Or any fork of MultiOgar for that matter that uses the Agario client.

You can even search in the Barbosik's issues for skins, you will see many who had the same problem as you do. Sorry, but as far as I know this bug cannot be fixed. Please check that your Raga.pw extension is in complete, working order.

**Closed** 2017-02-16 01:48 UTC
