### ISSUE TITLE
Any codes for Popsplits and doublesplits

### ISSUE THREAD

**Issue by VSabertail** [Megabyte918/MultiOgar-Edited#900] opened 2017-06-03 12:50 UTC
If anyone has a code for perfect popsplits and doublesplits give me the code and tell me where to put them im currently making a public server and i want to practice those with my friends

**Comment by FantasyIsBae** [comment] 2017-06-03 13:32
There is NO special code for popsplits.
Also a duplicate of many other issues.
Please look through them before making a new one.

**Comment by AlexHGaming** [comment] 2017-06-03 15:26
You can try reducing [this line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/Virus.js#L51)'s value, but if it goes below 1, the viruses will break.
And @FantasyIsBae is right, so many people have talked about this, so this will be issue from now on if such user made a related issue, they will be redirected to this.
@MastaCoder @Megabyte918 close.

**Closed** 2017-06-03 19:58 UTC

**Comment by ExobyteZOfficial** [comment] 2017-06-04 08:28
900th Issue lol
