### ISSUE TITLE
Pellet Mode Using P? Is that posible?

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#70] opened 2016-11-20 07:13 UTC
works?

**Comment by Megabyte918** [comment] 2016-11-20 07:22
Pellet mode does not exist. 
> Alright, since people are requesting it I guess I could start working on it, but I'm very busy right now. Still have a lot of features to add and bugs to fix so it might not be for a while until its implemented.

You've made 5 issues about pellet mode, do not make any more. I will add it when I am ready.
Duplicate of #8, #43, #45, #50, #62

**Closed by Megabyte918** 2016-11-20 07:22 UTC
