### ISSUE TITLE
Eh it was better before...

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#918] opened 2017-06-10 01:05 UTC
Was previously Push split  like in gota.io. If memory serves me it was on version 1.3.7-1.4.4. May try to get it back? If necessary I can give the file with these versions

**Comment by ExobyteZOfficial** [comment] 2017-06-10 02:36
NO ITS WAS NOT BEFORE ._.

**Comment by AlexHGaming** [comment] 2017-06-10 08:40
#465 refer to my issue here.

**Comment by AlexHGaming** [comment] 2017-06-10 08:41
Or change the `unshift` in playercell.js to `push`

**Comment by FantasyIsBae** [comment] 2017-06-10 08:42
Duplicate of #465 
If anything do what Alex said above.

**Closed by FantasyIsBae** 2017-06-10 08:42 UTC

**Comment by AlexHGaming** [comment] 2017-06-10 08:45
Read @FantasyIsBae's comment

**Comment by DeadLord1337** [comment] 2017-06-10 15:46
Or change the unshift in playercell.js to push - it does nothing does not work in gota io, I did push it a thousand times, not what is not changed...

**Comment by DeadLord1337** [comment] 2017-06-10 16:10
@AlexHGaming

**Comment by AlexHGaming** [comment] 2017-06-10 21:27
@DeadLord1337 Well it is still a duplicate of my gravitational splits issue, which relates to pushes and easier pops if needed.
