### ISSUE TITLE
Ultrasplit in MO-E

### ISSUE THREAD

**Issue by Hydra4dude** [Megabyte918/MultiOgar-Edited#1376] opened 2018-01-02 04:40 UTC
How do I put ultra split in MO-E, since the server does not recognize the minus sign in PlayerRecombineTime? Ex: PlayedRecombineTime: -999

**Comment by Agarian** [comment] 2018-01-02 08:23
Are you trying to make merging never happen, or instantly happen?

**Comment by AlexHGaming** [comment] 2018-01-02 11:46
Ok, firstly, discord server.
Secondly, put the recombine time to 0, and lower the split velocity
@Megabyte918 close

**Comment by AlexHGaming** [comment] 2018-01-02 11:50
Also a dupe

**Comment by AlexHGaming** [comment] 2018-01-02 11:53
weSmart

**Comment by Megabyte918** [comment] 2018-01-02 11:53
Duplicate of #792 and #862

**Closed by Megabyte918** 2018-01-02 11:53 UTC
Labels: Question

**Comment by Agarian** [comment] 2018-01-02 15:53
k

**Comment by Valdex** [comment] 2018-02-11 09:28
@Hydra4dude ULTRASPLIT WRITEN ON MULTIOGARBLOB BY F0RIS

**Comment by Valdex** [comment] 2018-02-11 09:29
@Hydra4dude its rly copy of ultra from bubla and gaver

**Comment by Agarian** [comment] 2018-02-11 09:42
k

**Comment by AlexHGaming** [comment] 2018-02-11 10:44
k
