### ISSUE TITLE
Pushsplit on multi-ogar edited ?

### ISSUE THREAD

**Issue by EarthAgar** [Megabyte918/MultiOgar-Edited#884] opened 2017-05-29 05:33 UTC
please dont close i have found many comments on other issues about this and i am very curious as well how do we make  pushsplit like on gota.io on multi-ogar edited ? if you dont know what it is its basicly this here : https://youtu.be/PB0s5wrXSRs its where you are on somone and next to virus and split once and it some how overlap them and boom pushsplit how tho ? :(

**Comment by EarthAgar** [comment] 2017-05-29 05:33
Plz help support this issue by submiting your oppinion as well thanks i want this answered

**Comment by freaky767** [comment] 2017-05-29 07:25
technically i would call this a duplicate, but i actually dont know how to make pushsplit work

**Comment by AlexHGaming** [comment] 2017-05-29 07:57
Duplicate of #465 (which is my issue)
there are more duplicates, but please search for other issues for your answer.

**Closed** 2017-05-29 20:47 UTC

**Comment by EarthAgar** [comment] 2017-06-06 05:33
sorry i have been searching for a while
