### ISSUE TITLE
Very stupid bots

### ISSUE THREAD

**Issue by t11tanYT** [Megabyte918/MultiOgar-Edited#613] opened 2017-02-28 09:30 UTC
bots always split and "dance" 
Make bots split system smarter
if i have minions all bots always split into it

**Comment by Gigabyte918** [comment] 2017-02-28 14:50
Duplicate!

**Comment by MastaCoder** [comment] 2017-02-28 22:22
Cy@

**Comment by Luka967** [comment] 2017-03-01 01:25
lel

**Comment by Megabyte918** [comment] 2017-03-01 05:30
I'm planning on working on it once everything else is finished and there is some performance to spare for smarter AI. Also this is a duplicate of many other issues, so I am closing.

**Closed by Megabyte918** 2017-03-01 05:30 UTC
