### ISSUE TITLE
Minion pellet mode

### ISSUE THREAD

**Issue by XtremePlayzCODE** [Megabyte918/MultiOgar-Edited#43] opened 2016-11-12 00:49 UTC
Could you add a minion pellet mode maybe by pressing Q two times really fast, like seeing how many times Q was pressed in a short amount of time, (e.g. 2 sec) and turning the minions into bots that only collect pellets temporarily until turned off

**Comment by NameYT** [comment] 2016-11-12 00:56
DUPLICATE of #8

**Comment by XtremePlayzCODE** [comment] 2016-11-12 00:57
"If many people request that I add the minions collecting pellets feature, I may add it." - Megabyte918. That's why I have a dupe.

**Comment by NameYT** [comment] 2016-11-12 01:00
@XtremePlayzCODE just message it on #8

**Comment by XtremePlayzCODE** [comment] 2016-11-12 01:00
Why don't you

**Comment by XtremePlayzCODE** [comment] 2016-11-12 01:01
#8 done

**Comment by NameYT** [comment] 2016-11-12 01:01
@XtremePlayzCODE Already Messaged it :p lets wait for @Megabyte918 to reply my options are when you click "p" as a collect pellet mode like extensions that would be awesome

**Comment by XtremePlayzCODE** [comment] 2016-11-12 01:01
Say same

**Comment by XtremePlayzCODE** [comment] 2016-11-12 01:02
#WeWantPelletMode

**Comment by NameYT** [comment] 2016-11-12 01:02
@XtremePlayzCODE When you click "P" Minions will automatically collect pellets :)
http://agar.io/?ip=sambyonweed-samby6667851.codeanyapp.com:3000
Join my server if you want

**Comment by XtremePlayzCODE** [comment] 2016-11-12 01:02
Wait wait, they do?

**Comment by XtremePlayzCODE** [comment] 2016-11-12 01:02
Give me minions, i am XPC

**Comment by XtremePlayzCODE** [comment] 2016-11-12 01:05
startmass 43 plz

**Comment by NameYT** [comment] 2016-11-12 01:06
k

**Comment by XtremePlayzCODE** [comment] 2016-11-12 01:07
YAS

**Comment by NameYT** [comment] 2016-11-12 01:07
Wait i should make a Sponsor video xD

**Comment by XtremePlayzCODE** [comment] 2016-11-12 01:10
TOO MUCH LAG

**Comment by XtremePlayzCODE** [comment] 2016-11-12 01:11
andddddd its offline

**Comment by Fantasy-Agario** [comment] 2016-11-12 01:12
RIP

**Comment by Jhair2015** [comment] 2016-11-12 02:00
is stupid add the feature

**Comment by NameYT** [comment] 2016-11-12 02:08
ADDDDDDDDDDDDDDDDDDDDD

**Comment by XtremePlayzCODE** [comment] 2016-11-12 02:09
What?

**Closed** 2016-11-12 06:41 UTC
