### ISSUE TITLE
Web console close by itself when attempting to start it

### ISSUE THREAD

**Issue by duwayy** [Megabyte918/MultiOgar-Edited#743] opened 2017-04-07 15:40 UTC
Hi all,
2nd time I try to use the webconsole.
I followed readme, changed Ip&ports in console-plus.js to have console running on port 1236 (multiogar on 1235).
But, problem, after launching Multiogar, doing a "node console-plus.js" give me "consoleServer is listening on port 1236" and then it stops by itself immediatly.
I also noticed than if Multiogar isn't launched, console will not close by itself...

Any help ?
Thanks

**Comment by Jhair2015** [comment] 2017-04-07 15:43
Are you trying to make your server on Linux?

**Comment by duwayy** [comment] 2017-04-07 15:50
Ubuntu yes

**Comment by duwayy** [comment] 2017-04-07 16:07
Is web console Windows-only ?

**Comment by AlexHGaming** [comment] 2017-04-07 16:10
cd src
sudo node index

**Comment by duwayy** [comment] 2017-04-07 16:36
Multiogar is already started. I trid starting it from index.js instead of lin-Start.sh but it's the same, console close when starting it

**Comment by MastaCoder** [comment] 2017-04-07 19:49
There has to be an error for it to close automatically. No?

**Comment by Jhair2015** [comment] 2017-04-07 19:50
I suppose he uses Tyler's authorestart @MastaCoder

**Comment by duwayy** [comment] 2017-04-07 19:54
No, anything, no error and no log..

**Comment by Megabyte918** [comment] 2017-04-11 15:14
@duwayy Try viewing other issues regarding web consoles and see if your issue is within one of them.

**Comment by duwayy** [comment] 2017-04-11 22:39
I did'nt found anything, maybe the webconsole author would know why it happen?..

**Comment by MastaCoder** [comment] 2017-04-15 02:00
Try on a different VPS or computer. This is due to something installed incorrectly or the OS is closing by itself. (Sometimes they do it when you're at max limit of RAM or other resources.)

Can't reproduce this bug.

**Closed by MastaCoder** 2017-04-15 02:00 UTC
