### ISSUE TITLE
Agario private servers not working just saying connecting

### ISSUE THREAD

**Issue by koda** [Megabyte918/MultiOgar-Edited#904] opened 2017-06-04 15:10 UTC
![xzlol](https://cloud.githubusercontent.com/assets/23435125/26762812/50046ea2-4940-11e7-8e27-7e08f021e235.JPG)

any fixes?

**Comment by koda** [comment] 2017-06-04 15:16
Anyone has a fix for yellow rings?

**Comment by AlexHGaming** [comment] 2017-06-04 15:45
Yellow rings is a duplicate of an issue on this repo
and make sure you are logged out of facebook/google before accessing the server, in which this is a duplicate aswell.

**Comment by koda** [comment] 2017-06-04 16:14
So is there a way to fix it? the yellow rings

**Comment by DeadLord1337** [comment] 2017-06-04 16:24
My issue ))[#885](https://github.com/Megabyte918/MultiOgar-Edited/issues/885)

**Closed** 2017-06-04 16:44 UTC
