### ISSUE TITLE
Dont work agar client! Why?

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#420] opened 2017-01-18 19:35 UTC
Why not connect the client Agario?
Do not write that another client, you can use...

**Comment by AlexHGaming** [comment] 2017-01-18 19:47
because of the new update

**Comment by ZfsrGhS953** [comment] 2017-01-18 19:47
This is both invalid and a duplicate of #418 , it's an issue with Moneyclip.

**Comment by DeadLord1337** [comment] 2017-01-18 19:53
soon you correct this mistake likely?

**Comment by ItzLevvie** [comment] 2017-01-18 21:14
Download the latest MultiOgar-Edited.... it should work now.

**Comment by Agarian** [comment] 2017-01-18 21:41
@Megabyte918 close please lol

**Closed** 2017-01-18 21:52 UTC
