### ISSUE TITLE
help me :( 

### ISSUE THREAD

**Issue by imnotNxhz1** [Megabyte918/MultiOgar-Edited#526] opened 2017-02-10 04:07 UTC
can help me with this error https://s28.postimg.org/dgyspaea5/234.png

**Comment by Luka967** [comment] 2017-02-10 04:17
Duplicate of #492

**Comment by Agarian** [comment] 2017-02-10 18:15
@imnotNxhz1 Look in #492 for the answer.

**Closed** 2017-02-10 20:39 UTC
