### ISSUE TITLE
what ?

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#160] opened 2016-12-06 17:34 UTC
When I ban many ip, the server is bug , 
Says connecting when there are only 50 players of 200 , 
Only happens in versions 1.4 onwards

**Comment by Megabyte918** [comment] 2016-12-06 20:39
@PsycoYT I could not reproduce this, it just says "disconnected" for me, then later they disappear from the playerlist.

**Comment by PsycoYT** [comment] 2016-12-06 21:58
appears 'connecting' as if the server was full , with version 1.3.7 does not happen that

**Comment by Megabyte918** [comment] 2016-12-06 22:18
@PsycoYT can you post a photo? I've tried to make this happen many times but no luck.

**Comment by PsycoYT** [comment] 2016-12-06 22:44
Does not send any errors in console 

only said in the client 'Connecting' with 1.4.0 - 1.4.2 versions

**Comment by PsycoYT** [comment] 2016-12-06 22:44
in ogar.pw

**Comment by Megabyte918** [comment] 2016-12-06 23:51
@PsycoYT I can't fix something that isn't broken.. I haven't been able to reproduce this bug. Try changing the "logVerbosity" config to 5, then go into the logs and show me the latest one. There might be an error there. If there is none, try using a different client and see what happens, if it doesnt happen then that means it's a problem with the ogar.pw client. Is this reocurring? And what steps did you take to find this bug? Please explain in great detail.

**Comment by Megabyte918** [comment] 2016-12-06 23:53
Is anyone else having the same problem?

**Comment by MastaCoder** [comment] 2016-12-07 00:03
> appears 'connecting' as if the server was full

Does connecting keep showing up and going away? Usually that's if you're banned, server is full, etc. If it's just a straight connection, most likely the connection is down.

**Comment by Jhair2015** [comment] 2016-12-07 00:36
@Megabyte918  Yep, i have a similar problem

**Comment by Megabyte918** [comment] 2016-12-10 01:13
Nope, still can't get it to happen. Anyone ELSE experiencing the same problem?

**Comment by Gimmo** [comment] 2016-12-10 18:53
[![1.png](https://s18.postimg.org/5hvrt041l/image.png)](https://postimg.org/image/4sczgn3hx/)
[![2.png](https://s28.postimg.org/wu9fo3b3x/image.png)](https://postimg.org/image/qtbqr0ohl/)

**Comment by Jhair2015** [comment] 2016-12-10 19:10
Alis.io client has been delete border's...

**Comment by Gimmo** [comment] 2016-12-10 19:15
Sorry, I don't understand what you talking about.

**Comment by MastaCoder** [comment] 2016-12-10 19:48
I don't get what you're trying to show in those screenshots @Gimmo

**Comment by Gimmo** [comment] 2016-12-10 19:54
Wrong thread...... :(  Try to move to correct place.

**Comment by Megabyte918** [comment] 2016-12-11 23:19
Closing this for lack of information..

**Closed by Megabyte918** 2016-12-11 23:19 UTC
