### ISSUE TITLE
Anyway to call command from javascript

### ISSUE THREAD

**Issue by MineMooreALT** [Megabyte918/MultiOgar-Edited#770] opened 2017-04-18 00:30 UTC
Hello is there anyway to use a command in the gameserver file
for example
`setTimeout (function() { board heelloo }, 200000);`

**Comment by Tyler3D** [comment] 2017-04-18 00:32
Duplicate of https://github.com/Megabyte918/MultiOgar-Edited/issues/691

**Closed** 2017-04-18 00:33 UTC
