### ISSUE TITLE
The Mothercell issues

### ISSUE THREAD

**Issue by ogarfan69** [Megabyte918/MultiOgar-Edited#1183] opened 2017-08-08 16:56 UTC
**Dear Mega,Recently I'm having a problem in experimental mode In your multiogar server. the problems are-
1. when the mothercells are untouched(in their default mass orlike no body has feeded the mothercell), They don't even eject any pettels
2.when the mothercells get big (like 20000 mass) they stop ejecting pettels and sit there forever doing nothing. Please Fix this.Thanks!
![2](https://user-images.githubusercontent.com/30747392/29084077-85cb64fc-7c88-11e7-9896-c8efa8d54137.JPG)
![capturev](https://user-images.githubusercontent.com/30747392/29084082-8b40c972-7c88-11e7-954a-1962d707ce6b.JPG)

P.S i have tried it on- 
http://agar.io/?ip=127.0.0.1:443
http://agarahg.tk**

**Comment by FantasyIsBae** [comment] 2017-08-08 17:16
The issue is with the server max food limit, try increasing ```foodMaxAmount ``` in the `gameserver.ini` file and see if that helps :)

**Comment by ogarfan69** [comment] 2017-08-09 06:38
**I did that,But that didn't help :( can you pls try fixing it?**

**Comment by FantasyIsBae** [comment] 2017-08-09 10:36
Okay

**Comment by FantasyIsBae** [comment] 2017-08-09 10:40
Remove:
[This Line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/MotherCell.js#L37)[This Line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/MotherCell.js#L38)[This Line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/MotherCell.js#L39)[And This Line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/MotherCell.js#L40)

**Comment by FantasyIsBae** [comment] 2017-08-09 10:58
This will make the food on the server and even make the server lag, but this is the only way i think you could fix your issue.

**Comment by FantasyIsBae** [comment] 2017-08-11 12:43
Unanswered , closing.

**Closed by FantasyIsBae** 2017-08-11 12:43 UTC

**Comment by AlexHGaming** [comment] 2017-08-12 14:02
_http://agarahg.tk_
swagelicious
