### ISSUE TITLE
Some bugs happen!

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#651] opened 2017-03-08 02:14 UTC
I know that the minions have been removed from the leaderboard to minimize the lag, but could you make that happen at the time of spectate?

There are problems to spawn the player, there are times that it is necessary to give several times to play

Skins do not work in another protocol, or well that could fix it with the other problem in issues xD, do not tell me duplicate :p

**Comment by Tyler3D** [comment] 2017-03-08 02:19
@Jhair2015 The skins are fixed in my fork. I'm just waiting for @Megabyte918 to take a look at it. The spawning problem. I could not reproduce. Were you using the agar.io client? And doing something like what you said might cause even more lag then more because of the constant checks for spectate mode

**Comment by Jhair2015** [comment] 2017-03-08 02:23
@Tyler3D Ok thanks :)

**Comment by Jhair2015** [comment] 2017-03-08 02:24
I have something more to add to these buga,
To have minions some usually appear with much more mass than indicated in gameserver.ini, that is usually more visible if you have minions for above 100 @Megabyte918

**Comment by Megabyte918** [comment] 2017-03-08 06:35
> I know that the minions have been removed from the leaderboard to minimize the lag, but could you make that happen at the time of spectate?

This could cause issues with uneven update times as any player could hit spectate at any time, it would be best just to add visible node calculations for them back all together.
> There are problems to spawn the player, there are times that it is necessary to give several times to play

This is an issue with the safe spawning system, I have fixed this on my private version and will commit the fixes when I am ready-- but you shouldn't experience this very often unless your server is packed.

**Comment by Jhair2015** [comment] 2017-03-08 06:51
@Megabyte918 It happens when mass is expelled and from it the minions grow three times their size, I can record a video?

**Comment by Megabyte918** [comment] 2017-03-08 07:14
@Jhair2015 What version are you running? Have you edited anything in the server?

**Comment by Jhair2015** [comment] 2017-03-08 07:55
@Megabyte918 the last version and No

**Comment by FlareYT** [comment] 2017-03-10 18:13
@Jhair2015 , I fixxed the Skin Issue using the old PacketHandler.js .
I don't know if its also works for you.

**Comment by Jhair2015** [comment] 2017-03-10 20:33
@FlareYT Since what version?

**Comment by FlareYT** [comment] 2017-03-10 21:07
Well im using @Tyler3D Version , and I took the [PacketHandler](http://pastebin.com/5KG6xL72) from the Version 1.4.8 :

**Comment by Megabyte918** [comment] 2017-03-11 16:04
@Jhair2015 Try using the latest version along with an **unedited** gameserver.ini, you should not experience these bugs anymore. I did the same and I could not reproduce the minions bug

**Closed** 2017-03-23 21:31 UTC

**Comment by Luka967** [comment] 2017-03-23 21:45
lmao

**Comment by MastaCoder** [comment] 2017-03-23 21:55
:trollface:

**Comment by Jhair2015** [comment] 2017-03-23 22:16
:trollface:
