### ISSUE TITLE
Better popsplits

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#776] opened 2017-04-19 12:12 UTC
i think that this improve the popsplit in playercell onAdd function , above of the unshift

`this.gameServer.nodesPlayer.reverse(this);`

work fine for me

**Comment by HyperAgar** [comment] 2017-04-19 12:39
You can get realistic physics and better popsplits by going into the gameserver.ini and changing
the splitVelocity : 715
This change is done under the player section of the gameserver.ini

**Comment by gyeyoqu** [comment] 2017-04-19 12:48
@HyperAgar  hmm ok

**Comment by HyperAgar** [comment] 2017-04-19 12:55
It works

**Comment by Megabyte918** [comment] 2017-04-19 13:27
Duplicate of #766

**Closed by Megabyte918** 2017-04-19 13:27 UTC

**Comment by gyeyoqu** [comment] 2017-04-19 14:12
@Megabyte918  
I do not see the duplicate

**Comment by Megabyte918** [comment] 2017-04-19 17:02
@gyeyoqu Sorry! My bad. I read it as though it was the same as #766 xD I should really start reading these more carefully. But to answer your issue, it would be best to keep PlayerCell.js the way it is with the unshift and find a workaround for popsplits in the `mainLoop` function of GameServer to keep the fixes for doublesplits, etc and to not cause any future bugs (or maybe fix a few). As discussed in #723.

**Comment by gyeyoqu** [comment] 2017-04-20 09:56
its ok , im learning js quickly, in a future i can help

**Comment by gyeyoqu** [comment] 2017-04-20 10:15
@Megabyte918 
Mainly, where should I put emphasis to solve the popsplit?

**Comment by Megabyte918** [comment] 2017-04-21 00:14
@gyeyoqu The `mainLoop` function in GameServer.js needs to be edited along with a refactoring of the collision engine. Eat collisions should be processed slower than rigid collision processing. Currently eat collision processing happens too quickly which has a big effect on popsplits. Refactoring the collision engine should also have an effect on it but I'm not so sure yet.
