### ISSUE TITLE
Spawning glitch

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#836] opened 2017-05-11 19:34 UTC
SOMETIMES AND RARELY, when I die, 15 pieces are dead, but 1 is alive and still "kills me". When I spawn in, the view is extremely bugged and I would have to split many times to "be alive again". Did this ever happen to anyone else?

**Comment by Exobyte918** [comment] 2017-05-12 01:11
Same lol u have discord can i join?

**Comment by AlexHGaming** [comment] 2017-05-12 05:51
AlexHGaming#0849

**Comment by gyeyoqu** [comment] 2017-05-12 09:55
@AlexHGaming  i can fix if u tell me where is the function

**Comment by gyeyoqu** [comment] 2017-05-12 10:13
@AlexHGaming im not have that bug with last version

**Comment by Exobyte918** [comment] 2017-05-12 11:51
`var = fixcode;)
`

**Comment by AdaptCharm** [comment] 2017-05-12 14:37
@gyeyoqu Add me on Discord, Atmosphere™#3482

**Comment by AlexHGaming** [comment] 2017-05-12 15:16
@gyeyoqu I am not completely sure where the function for spawning people into a server is in. Also, this happened on my client, also same to the vanilla. So it is server sided. I do not know where the function is, and I'm using the latest version (1.6.1) and not edited any of the spawning systems.

**Comment by MastaCoder** [comment] 2017-05-14 18:57
Can anybody reproduce. Works fine for me.

**Comment by HyperAgar** [comment] 2017-05-14 21:44
@MastaCoder please go to my issue so that i can help with this one. You closed it :/

**Comment by Megabyte918** [comment] 2017-05-24 00:23
I also cannot reproduce this. Anyone else experiencing the same issue?

**Comment by Gigabyte918** [comment] 2017-05-28 09:34
no this dosent happens to mea

**Comment by Exobyte918** [comment] 2017-05-28 11:20
dis happens to me ;-;

**Comment by AdaptCharm** [comment] 2017-05-29 22:18
Never happened to me

**Comment by MastaCoder** [comment] 2017-05-30 00:36
Can't reproduce. Until this becomes major, it can't be an issue.

**Closed by MastaCoder** 2017-05-30 00:36 UTC
Labels: Cannot Reproduce
