### ISSUE TITLE
Update for Ogarclient

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#615] opened 2017-02-28 18:50 UTC
@Megabyte918  YOU CAN MAKE THIS UPDATE TO SUPPORT UNICODE?

https://github.com/JaraLowell/OgarServ/commit/61e716272c8c5303bdda622483bdbd62d88aba0b

**Comment by AlexHGaming** [comment] 2017-02-28 19:25
No. We don't support clients.

**Comment by Tyler3D** [comment] 2017-02-28 20:06
Ummm ask @JaraLowell Not @Megabyte918

**Comment by MastaCoder** [comment] 2017-02-28 22:05
@Tyler3D he means make M-ED support Unicode.

Short Answer: No.
Long Answer: No we support official client.

**Comment by Luka967** [comment] 2017-02-28 22:14
@MastaCoder He's using my protocol 6 client and wants to replace strings unicode -.-'

**Comment by JaraLowell** [comment] 2017-02-28 22:36
Do not ask @JaraLowell >.< go ask @Tyler3D 

And actually agar.io supports Unicode names :3 (Emoji)

**Comment by gyeyoqu** [comment] 2017-02-28 23:59
jaralowell rekt all ass

**Comment by MastaCoder** [comment] 2017-03-01 01:53
what? lmao

**Comment by Megabyte918** [comment] 2017-03-01 05:20
@gyeyoqu Duplicate of #530, and if you want unicode add the code from @JaraLowell's updates.

**Closed by Megabyte918** 2017-03-01 05:20 UTC
