### ISSUE TITLE
The connection is suddenly interrupted

### ISSUE THREAD

**Issue by ARBCells** [Megabyte918/MultiOgar-Edited#422] opened 2017-01-19 16:27 UTC
After about 10-60 minutes the server lose connection and no one can connect (''connecting'' starts flashing)

The MultiOgar-Edited command prompt is still running as usual when the connection hangs and gives no errors.

How server logs looks like: https://goo.gl/KLunlx

What is causing this problem and is there any solution?

Facts:
I use the latest version 1.5.0 and hosting server with Windows Server 2012 R2.

Thanks in advance,
Joseph

**Comment by Agarian** [comment] 2017-01-19 16:45
Duplicate of #406 
@Megabyte918 is aware of this problem

**Comment by AlexHGaming** [comment] 2017-01-19 20:59
This happens to me if I use codeanywhere
When I used to have the solo server files for MultiOgar-Edited it never disconnected me, codeanywhere disconnects me after 10 mins.
It's probably because of the new moneyclip agar update. Try playing on different clients such as astr.io or nbk.io and you should be fine.
@Megabyte918 Close.

**Comment by Jhair2015** [comment] 2017-01-19 22:18
@AlexHGaming Do you have skype or any means to communicate with you?

**Comment by ARBCells** [comment] 2017-01-20 11:59
=== Started 2017-01-19T17-28-39-725 ===
[INFO ][17:28:39] 0 IP ban records loaded.
[WARN ][17:28:39] User account "Local Administrator" disabled
[WARN ][17:28:39] User account "Local Moderator" disabled
[WARN ][17:28:39] User account "Local User" disabled
[INFO ][17:28:39] 0 user records loaded.
[INFO ][17:28:39] 419 bad words loaded
[INFO ][17:28:39] [1m[32mMultiOgar-Edited 1.5.0[37m - An open source multi-protocol ogar server[0m
[INFO ][17:28:39] WebSocket: ws
[INFO ][17:28:39] Started stats server on port 88
[INFO ][17:28:39] Listening on port 49186
[INFO ][17:28:39] Current game mode is Free For All
[NONE ][17:29:04] CONNECTED    81.228.32.169:55793, origin: "http://agar.io"
[NONE ][17:30:48] CONNECTED    193.81.108.58:58468, origin: "http://agar.io"
[NONE ][17:31:17] DISCONNECTED 193.81.108.58:58468, code: 1001, reason: "", name: ""
[NONE ][17:34:42] CONNECTED    95.91.157.21:54214, origin: "http://agar.io"
[NONE ][17:34:47] DISCONNECTED 95.91.157.21:54214, code: 1006, reason: "", name: ""
[NONE ][17:35:34] DISCONNECTED 81.228.32.169:55793, code: 1001, reason: "", name: "Kristoffer"
[NONE ][17:41:41] CONNECTED    85.212.94.78:55873, origin: "http://agar.io"
[NONE ][17:41:46] CONNECTED    85.212.94.78:55902, origin: "http://agar.io"
[NONE ][17:46:41] DISCONNECTED 85.212.94.78:55873, code: 1000, reason: "Connection timeout", name: ""
[NONE ][18:00:41] DISCONNECTED 85.212.94.78:55902, code: 1001, reason: "", name: "BOTS ARE BACK!"
[NONE ][18:03:16] CONNECTED    207.71.24.66:16621, origin: "http://agar.io"
[NONE ][18:03:17] CONNECTED    179.183.82.13:29840, origin: "http://agar.io"
[NONE ][18:18:20] CONNECTED    80.42.120.214:55765, origin: "http://agar.io"
[NONE ][18:18:24] CONNECTED    80.42.120.214:55789, origin: "http://agar.io"
[NONE ][18:19:18] DISCONNECTED 80.42.120.214:55765, code: 1001, reason: "", name: ""
[NONE ][18:19:18] DISCONNECTED 80.42.120.214:55789, code: 1001, reason: "", name: "Ghost"
[NONE ][18:19:34] CONNECTED    80.42.120.214:55857, origin: "http://agar.io"
[NONE ][18:21:48] DISCONNECTED 207.71.24.66:16621, code: 1006, reason: "undefined", name: "F̐̈a̐̈z̐̈e̐̈ up"
[NONE ][18:54:03] CONNECTED    176.218.103.68:62208, origin: "http://agar.io"
[NONE ][18:54:25] CONNECTED    176.218.103.68:62228, origin: "http://agar.io"
[NONE ][18:54:29] CONNECTED    176.218.103.68:62231, origin: "http://agar.io"
[NONE ][18:54:32] DISCONNECTED 176.218.103.68:62228, code: 1001, reason: "", name: ""
[NONE ][18:54:32] DISCONNECTED 176.218.103.68:62208, code: 1001, reason: "", name: ""
[NONE ][18:54:32] DISCONNECTED 176.218.103.68:62231, code: 1001, reason: "", name: ""
[NONE ][18:54:42] CONNECTED    80.42.120.214:56082, origin: "http://agar.io"
[NONE ][18:54:42] CONNECTED    176.218.103.68:62364, origin: "http://agar.io"
[NONE ][18:54:45] CONNECTED    179.183.82.13:29828, origin: "http://agar.io"
[NONE ][18:54:46] CONNECTED    176.218.103.68:62376, origin: "http://agar.io"
[NONE ][18:54:46] CONNECTED    80.42.120.214:56091, origin: "http://agar.io"
[NONE ][18:54:48] DISCONNECTED 80.42.120.214:56091, code: 1001, reason: "", name: ""
[NONE ][18:54:48] DISCONNECTED 80.42.120.214:55857, code: 1001, reason: "", name: "Ghost"
[NONE ][18:54:48] DISCONNECTED 80.42.120.214:56082, code: 1001, reason: "", name: ""
[NONE ][18:55:15] CONNECTED    80.42.120.214:56178, origin: "http://agar.io"
[NONE ][18:55:18] DISCONNECTED 179.183.82.13:29840, code: 1001, reason: "", name: "Cσяd绳一ƬψƬ🌌"
[NONE ][18:55:18] DISCONNECTED 179.183.82.13:29828, code: 1001, reason: "", name: ""
[NONE ][18:56:03] DISCONNECTED 176.218.103.68:62364, code: 1001, reason: "", name: ""
[NONE ][18:56:03] DISCONNECTED 176.218.103.68:62376, code: 1001, reason: "", name: ""
[NONE ][18:56:10] CONNECTED    179.183.82.13:29908, origin: "http://agar.io"
[NONE ][18:56:22] CONNECTED    80.42.120.214:56191, origin: "http://agar.io"
[NONE ][18:56:31] DISCONNECTED 80.42.120.214:56191, code: 1001, reason: "", name: ""
[NONE ][18:56:31] DISCONNECTED 80.42.120.214:56178, code: 1001, reason: "", name: ""
[NONE ][18:56:58] DISCONNECTED 179.183.82.13:29908, code: 1001, reason: "", name: ""
[NONE ][18:57:00] CONNECTED    80.42.120.214:56276, origin: "http://agar.io"
[NONE ][18:57:44] DISCONNECTED 80.42.120.214:56276, code: 1001, reason: "", name: ""
[NONE ][18:57:59] CONNECTED    80.42.120.214:56371, origin: "http://agar.io"
[NONE ][18:59:21] DISCONNECTED 80.42.120.214:56371, code: 1001, reason: "", name: ""
[NONE ][19:00:06] CONNECTED    80.42.120.214:56636, origin: "http://agar.io"
[NONE ][19:01:10] DISCONNECTED 80.42.120.214:56636, code: 1001, reason: "", name: ""
[NONE ][19:03:41] CONNECTED    80.42.120.214:56920, origin: "http://agar.io"
[NONE ][19:03:46] DISCONNECTED 80.42.120.214:56920, code: 1001, reason: "", name: ""
[NONE ][19:30:46] CONNECTED    88.180.40.164:55749, origin: "http://agar.io"
[NONE ][19:31:13] DISCONNECTED 88.180.40.164:55749, code: 1001, reason: "", name: ""
[NONE ][19:39:48] CONNECTED    80.42.120.214:59660, origin: "http://agar.io"
[NONE ][19:40:10] DISCONNECTED 80.42.120.214:59660, code: 1001, reason: "", name: ""
[NONE ][19:40:14] CONNECTED    88.180.40.164:56751, origin: "http://agar.io"
[NONE ][19:40:41] DISCONNECTED 88.180.40.164:56751, code: 1001, reason: "", name: ""
[NONE ][19:58:26] CONNECTED    2.100.62.54:64036, origin: "http://agar.io"
[NONE ][19:59:14] DISCONNECTED 2.100.62.54:64036, code: 1001, reason: "", name: ""
[NONE ][20:41:01] CONNECTED    207.71.24.66:48557, origin: "http://agar.io"
[NONE ][20:41:02] CONNECTED    207.71.24.66:6361, origin: "http://agar.io"
[NONE ][20:41:30] DISCONNECTED 207.71.24.66:48557, code: 1001, reason: "", name: ""
[NONE ][20:41:30] DISCONNECTED 207.71.24.66:6361, code: 1001, reason: "", name: ""
[NONE ][20:41:39] CONNECTED    207.71.24.66:15036, origin: "http://agar.io"
[NONE ][20:41:41] CONNECTED    207.71.24.66:15987, origin: "http://agar.io"
[NONE ][20:42:05] DISCONNECTED 207.71.24.66:15987, code: 1001, reason: "", name: ""
[NONE ][20:42:17] CONNECTED    207.71.24.66:40394, origin: "http://agar.io"
[NONE ][20:42:21] CONNECTED    207.71.24.66:14108, origin: "http://agar.io"
[NONE ][20:42:29] DISCONNECTED 207.71.24.66:40394, code: 1001, reason: "", name: ""
[NONE ][20:45:02] CONNECTED    207.71.24.66:24206, origin: "http://agar.io"
[NONE ][20:45:26] DISCONNECTED 207.71.24.66:14108, code: 1001, reason: "", name: ""
[NONE ][20:45:39] CONNECTED    207.71.24.66:38422, origin: "http://agar.io"
[NONE ][20:45:53] DISCONNECTED 207.71.24.66:38422, code: 1001, reason: "", name: ""
[NONE ][20:46:14] CONNECTED    207.71.24.66:18038, origin: "http://agar.io"
[NONE ][20:47:09] DISCONNECTED 207.71.24.66:15036, code: 1006, reason: "Connection timeout", name: ""
[NONE ][20:47:46] DISCONNECTED 207.71.24.66:18038, code: 1001, reason: "", name: ""
[NONE ][20:48:52] CONNECTED    207.71.24.66:44694, origin: "http://agar.io"
[NONE ][20:50:13] DISCONNECTED 207.71.24.66:44694, code: 1001, reason: "", name: ""
[NONE ][20:50:30] DISCONNECTED 207.71.24.66:24206, code: 1006, reason: "Connection timeout", name: ""
[NONE ][20:53:42] CONNECTED    83.216.145.187:52681, origin: "http://agar.io"
[NONE ][20:54:22] DISCONNECTED 83.216.145.187:52681, code: 1001, reason: "", name: ""
[NONE ][20:55:46] CONNECTED    83.216.145.187:53073, origin: "http://agar.io"
[NONE ][20:56:29] DISCONNECTED 83.216.145.187:53073, code: 1001, reason: "", name: ""
[NONE ][20:56:48] CONNECTED    83.216.145.187:53195, origin: "http://agar.io"
[NONE ][20:57:34] CONNECTED    149.154.226.217:8384, origin: "http://agar.io"
[NONE ][20:59:21] CONNECTED    207.71.24.66:19119, origin: "http://agar.io"
[NONE ][20:59:24] CONNECTED    90.231.166.246:51184, origin: "http://agar.io"
[NONE ][20:59:49] CONNECTED    90.231.166.246:51221, origin: "http://agar.io"
[NONE ][20:59:50] DISCONNECTED 90.231.166.246:51221, code: 1001, reason: "", name: ""
[NONE ][20:59:50] DISCONNECTED 90.231.166.246:51184, code: 1001, reason: "", name: ""
[NONE ][20:59:58] CONNECTED    90.231.166.246:51251, origin: "http://agar.io"
[NONE ][21:00:12] DISCONNECTED 207.71.24.66:19119, code: 1001, reason: "", name: ""
[NONE ][21:01:33] CONNECTED    149.154.226.217:10432, origin: "http://agar.io"
[NONE ][21:01:44] CONNECTED    149.154.226.217:8835, origin: "http://agar.io"
[NONE ][21:01:46] DISCONNECTED 83.216.145.187:53195, code: 1001, reason: "", name: ""
[NONE ][21:02:08] DISCONNECTED 149.154.226.217:8835, code: 1001, reason: "", name: ""
[NONE ][21:02:08] DISCONNECTED 149.154.226.217:8384, code: 1001, reason: "", name: ""
[NONE ][21:02:08] DISCONNECTED 149.154.226.217:10432, code: 1001, reason: "", name: ""
[NONE ][21:02:27] CONNECTED    24.63.69.247:49427, origin: "http://agar.io"
[NONE ][21:02:30] DISCONNECTED 24.63.69.247:49427, code: 1001, reason: "", name: ""
[NONE ][21:04:58] DISCONNECTED 90.231.166.246:51251, code: 1000, reason: "Connection timeout", name: ""
[NONE ][21:09:17] CONNECTED    176.67.219.147:27150, origin: "http://agar.io"
[NONE ][21:11:32] CONNECTED    41.250.172.36:17607, origin: "http://agar.io"
[NONE ][21:11:40] DISCONNECTED 41.250.172.36:17607, code: 1001, reason: "", name: ""
[NONE ][21:12:02] CONNECTED    41.250.172.36:17641, origin: "http://agar.io"
[NONE ][21:12:25] DISCONNECTED 41.250.172.36:17641, code: 1001, reason: "", name: ""
[NONE ][21:14:44] DISCONNECTED 176.67.219.147:27150, code: 1000, reason: "Connection timeout", name: ""
[NONE ][21:15:18] CONNECTED    207.71.24.66:47184, origin: "http://agar.io"
[NONE ][21:21:08] DISCONNECTED 207.71.24.66:47184, code: 1006, reason: "Connection timeout", name: ""
[NONE ][21:49:20] CONNECTED    41.250.172.36:19205, origin: "http://agar.io"
[NONE ][21:49:22] DISCONNECTED 41.250.172.36:19205, code: 1001, reason: "", name: ""
[NONE ][21:56:24] CONNECTED    83.216.145.187:58328, origin: "http://agar.io"
[NONE ][21:58:35] DISCONNECTED 83.216.145.187:58328, code: 1001, reason: "", name: ""
[NONE ][22:39:05] CONNECTED    189.177.84.9:53885, origin: "http://agar.io"
[NONE ][22:39:57] DISCONNECTED 189.177.84.9:53885, code: 1001, reason: "", name: ""
[NONE ][22:42:11] CONNECTED    189.177.84.9:54000, origin: "http://agar.io"
[NONE ][22:42:29] DISCONNECTED 189.177.84.9:54000, code: 1001, reason: "", name: ""
[NONE ][22:48:55] CONNECTED    189.177.84.9:54160, origin: "http://agar.io"
[NONE ][22:49:08] CONNECTED    189.177.84.9:54167, origin: "http://agar.io"
[NONE ][22:49:26] DISCONNECTED 189.177.84.9:54167, code: 1001, reason: "", name: ""
[NONE ][22:49:26] DISCONNECTED 189.177.84.9:54160, code: 1001, reason: "", name: ""
[NONE ][22:53:00] CONNECTED    189.177.84.9:54326, origin: "http://agar.io"
[NONE ][22:53:34] DISCONNECTED 189.177.84.9:54326, code: 1001, reason: "", name: ""
[NONE ][22:57:11] CONNECTED    189.177.84.9:54755, origin: "http://agar.io"
[NONE ][22:57:39] CONNECTED    189.177.84.9:54769, origin: "http://agar.io"
[NONE ][22:57:53] DISCONNECTED 189.177.84.9:54755, code: 1001, reason: "", name: ""
[NONE ][22:57:53] DISCONNECTED 189.177.84.9:54769, code: 1001, reason: "", name: ""
[NONE ][23:03:37] CONNECTED    189.177.84.9:54922, origin: "http://agar.io"
[NONE ][23:03:45] DISCONNECTED 189.177.84.9:54922, code: 1001, reason: "", name: ""
[NONE ][23:04:07] CONNECTED    108.231.136.98:50702, origin: "http://agar.io"
[NONE ][23:05:29] DISCONNECTED 108.231.136.98:50702, code: 1001, reason: "", name: ""
[NONE ][23:09:07] CONNECTED    189.177.84.9:55457, origin: "http://agar.io"
[NONE ][23:09:24] DISCONNECTED 189.177.84.9:55457, code: 1001, reason: "", name: ""
[NONE ][23:09:33] CONNECTED    189.177.84.9:55520, origin: "http://agar.io"
[NONE ][23:09:51] CONNECTED    189.177.84.9:55559, origin: "http://agar.io"
[NONE ][23:09:55] DISCONNECTED 189.177.84.9:55520, code: 1001, reason: "", name: ""
[NONE ][23:09:55] DISCONNECTED 189.177.84.9:55559, code: 1001, reason: "", name: ""
[NONE ][23:26:10] CONNECTED    50.154.69.192:53093, origin: "http://agar.io"
[NONE ][23:26:15] DISCONNECTED 50.154.69.192:53093, code: 1001, reason: "", name: ""
[NONE ][23:26:25] CONNECTED    50.154.69.192:53135, origin: "http://agar.io"
[NONE ][23:26:31] CONNECTED    50.154.69.192:53137, origin: "http://agar.io"
[NONE ][23:28:45] CONNECTED    74.64.83.249:59808, origin: "http://agar.io"
[NONE ][23:29:00] DISCONNECTED 74.64.83.249:59808, code: 1001, reason: "", name: ""
[NONE ][23:30:11] CONNECTED    74.64.83.249:59904, origin: "http://agar.io"
[NONE ][23:30:17] DISCONNECTED 74.64.83.249:59904, code: 1001, reason: "", name: ""
[NONE ][23:31:31] DISCONNECTED 50.154.69.192:53135, code: 1000, reason: "Connection timeout", name: ""
[NONE ][23:31:45] DISCONNECTED 50.154.69.192:53137, code: 1001, reason: "", name: ""
[NONE ][23:33:42] CONNECTED    74.64.83.249:60080, origin: "http://agar.io"
[NONE ][23:34:03] DISCONNECTED 74.64.83.249:60080, code: 1001, reason: "", name: ""
[NONE ][23:38:09] CONNECTED    24.227.238.18:27945, origin: "http://agar.io"
[NONE ][23:38:15] CONNECTED    24.227.238.18:7452, origin: "http://agar.io"
[NONE ][23:38:26] DISCONNECTED 24.227.238.18:7452, code: 1001, reason: "", name: ""
[NONE ][23:38:26] DISCONNECTED 24.227.238.18:27945, code: 1001, reason: "", name: ""
[NONE ][23:38:42] CONNECTED    24.227.238.18:32203, origin: "http://agar.io"
[NONE ][23:39:12] DISCONNECTED 24.227.238.18:32203, code: 1001, reason: "", name: ""
[NONE ][23:40:15] CONNECTED    24.227.238.18:17548, origin: "http://agar.io"
[NONE ][23:40:25] DISCONNECTED 24.227.238.18:17548, code: 1001, reason: "", name: ""
[NONE ][23:44:28] CONNECTED    74.64.83.249:60606, origin: "http://agar.io"
[NONE ][23:44:53] DISCONNECTED 74.64.83.249:60606, code: 1001, reason: "", name: ""
[NONE ][00:03:35] CONNECTED    24.227.238.18:32871, origin: "http://agar.io"
[NONE ][00:09:01] DISCONNECTED 24.227.238.18:32871, code: 1000, reason: "Connection timeout", name: ""
[NONE ][00:38:35] CONNECTED    99.57.22.12:49834, origin: "http://agar.io"
[NONE ][00:39:20] CONNECTED    99.57.22.12:49892, origin: "http://agar.io"
[NONE ][00:39:37] DISCONNECTED 99.57.22.12:49892, code: 1001, reason: "", name: ""
[NONE ][00:39:48] CONNECTED    99.57.22.12:49926, origin: "http://agar.io"
[NONE ][00:40:28] DISCONNECTED 99.57.22.12:49926, code: 1001, reason: "", name: ""
[NONE ][00:40:53] CONNECTED    99.57.22.12:49969, origin: "http://agar.io"
[NONE ][00:41:14] DISCONNECTED 99.57.22.12:49834, code: 1006, reason: "undefined", name: ""
[NONE ][00:42:46] DISCONNECTED 99.57.22.12:49969, code: 1001, reason: "", name: ""
[NONE ][00:46:45] CONNECTED    99.57.22.12:50080, origin: "http://agar.io"
[NONE ][00:52:33] DISCONNECTED 99.57.22.12:50080, code: 1006, reason: "Connection timeout", name: ""
[NONE ][02:09:03] CONNECTED    191.33.13.4:26765, origin: "http://agar.io"
[NONE ][02:11:45] DISCONNECTED 191.33.13.4:26765, code: 1001, reason: "", name: ""
[NONE ][02:12:22] CONNECTED    191.33.13.4:26920, origin: "http://agar.io"
[NONE ][02:12:35] DISCONNECTED 191.33.13.4:26920, code: 1001, reason: "", name: ""
[NONE ][02:13:09] CONNECTED    99.57.22.12:50765, origin: "http://agar.io"
[NONE ][02:13:23] DISCONNECTED 99.57.22.12:50765, code: 1001, reason: "", name: ""
[NONE ][02:13:48] CONNECTED    99.57.22.12:50852, origin: "http://agar.io"
[NONE ][02:14:21] DISCONNECTED 99.57.22.12:50852, code: 1001, reason: "", name: ""
[NONE ][02:55:47] CONNECTED    199.192.120.124:59131, origin: "http://agar.io"
[NONE ][03:00:17] CONNECTED    174.56.145.100:4053, origin: "http://agar.io"
[NONE ][03:00:38] DISCONNECTED 174.56.145.100:4053, code: 1001, reason: "", name: ""
[NONE ][03:00:54] DISCONNECTED 199.192.120.124:59131, code: 1001, reason: "", name: ""
[NONE ][03:01:14] CONNECTED    199.192.120.124:54944, origin: "http://agar.io"
[NONE ][03:01:28] CONNECTED    199.192.120.124:55055, origin: "http://agar.io"
[NONE ][03:01:30] DISCONNECTED 199.192.120.124:55055, code: 1009, reason: "Spam", name: ""
[NONE ][03:01:48] CONNECTED    199.192.120.124:55164, origin: "http://agar.io"
[NONE ][03:01:56] DISCONNECTED 199.192.120.124:55164, code: 1009, reason: "Spam", name: ""
[NONE ][03:02:05] CONNECTED    199.192.120.124:55247, origin: "http://agar.io"
[NONE ][03:02:17] CONNECTED    199.192.120.124:55323, origin: "http://agar.io"
[NONE ][03:02:46] DISCONNECTED 199.192.120.124:55323, code: 1001, reason: "", name: ""
[NONE ][03:02:46] DISCONNECTED 199.192.120.124:55247, code: 1001, reason: "", name: ""
[NONE ][03:02:46] DISCONNECTED 199.192.120.124:54944, code: 1001, reason: "", name: ""
[NONE ][04:39:29] CONNECTED    2.244.60.191:58240, origin: "http://agar.io"
[NONE ][04:39:37] DISCONNECTED 2.244.60.191:58240, code: 1001, reason: "", name: ""
[NONE ][05:17:40] CONNECTED    2.244.60.191:58397, origin: "http://agar.io"
[NONE ][05:18:00] DISCONNECTED 2.244.60.191:58397, code: 1001, reason: "", name: ""
[NONE ][05:18:14] CONNECTED    2.244.60.191:58446, origin: "http://agar.io"
[NONE ][05:18:20] DISCONNECTED 2.244.60.191:58446, code: 1001, reason: "", name: ""
[NONE ][09:41:44] CONNECTED    77.106.83.35:49861, origin: "http://agar.io"
[NONE ][09:42:20] CONNECTED    77.106.83.35:49902, origin: "http://agar.io"
[NONE ][09:47:18] DISCONNECTED 77.106.83.35:49861, code: 1000, reason: "Connection timeout", name: ""
[NONE ][09:47:36] DISCONNECTED 77.106.83.35:49902, code: 1000, reason: "Connection timeout", name: ""
[NONE ][10:19:18] CONNECTED    78.164.172.217:50546, origin: "http://agar.io"
[NONE ][10:24:25] DISCONNECTED 78.164.172.217:50546, code: 1000, reason: "Connection timeout", name: ""
[NONE ][11:24:42] CONNECTED    81.170.238.131:24566, origin: "http://agar.io"
[NONE ][11:24:46] DISCONNECTED 81.170.238.131:24566, code: 1001, reason: "", name: ""
[NONE ][12:28:35] CONNECTED    112.200.195.142:22642, origin: "http://agar.io"
[NONE ][12:28:49] DISCONNECTED 112.200.195.142:22642, code: 1001, reason: "", name: ""
[NONE ][12:51:30] CONNECTED    89.88.217.100:51696, origin: "http://agar.io"
[NONE ][12:51:46] DISCONNECTED 89.88.217.100:51696, code: 1001, reason: "", name: ""
[NONE ][12:52:05] CONNECTED    89.88.217.100:51809, origin: "http://agar.io"
[NONE ][12:57:08] DISCONNECTED 89.88.217.100:51809, code: 1000, reason: "Connection timeout", name: ""

**Comment by raphyjb** [comment] 2017-01-20 15:03
Hm nice ip adresses ;)

**Comment by ARBCells** [comment] 2017-01-20 16:48
Srsly.... 9 minutes this time. Please anyone help me?

=== Started 2017-01-20T17-00-55-417 ===
[INFO ][17:00:55] 0 IP ban records loaded.
[WARN ][17:00:55] User account "Local Administrator" disabled
[WARN ][17:00:55] User account "Local Moderator" disabled
[WARN ][17:00:55] User account "Local User" disabled
[INFO ][17:00:55] 0 user records loaded.
[INFO ][17:00:55] 419 bad words loaded
[INFO ][17:00:55] [1m[32mMultiOgar-Edited 1.5.0[37m - An open source multi-protocol ogar server[0m
[INFO ][17:00:55] WebSocket: ws
[INFO ][17:00:55] Started stats server on port 88
[INFO ][17:00:55] Listening on port 49186
[INFO ][17:00:55] Current game mode is Free For All
[NONE ][17:01:10] CONNECTED    81.228.32.169:62541, origin: "http://agar.io"
[NONE ][17:03:11] CONNECTED    88.188.109.57:62992, origin: "http://agar.io"
[NONE ][17:03:11] DISCONNECTED 88.188.109.57:62992, code: 1009, reason: "Spam", name: ""
[NONE ][17:03:16] CONNECTED    88.188.109.57:62996, origin: "http://agar.io"
[NONE ][17:03:24] CONNECTED    88.188.109.57:62999, origin: "http://agar.io"
[NONE ][17:03:32] DISCONNECTED 88.188.109.57:62996, code: 1001, reason: "", name: ""
[NONE ][17:03:32] DISCONNECTED 88.188.109.57:62999, code: 1001, reason: "", name: ""
[NONE ][17:03:55] CONNECTED    88.188.109.57:63138, origin: "http://agar.io"
[NONE ][17:03:55] DISCONNECTED 88.188.109.57:63138, code: 1009, reason: "Spam", name: ""
[NONE ][17:03:58] CONNECTED    88.188.109.57:63142, origin: "http://agar.io"
[NONE ][17:04:09] CONNECTED    88.188.109.57:63144, origin: "http://agar.io"
[NONE ][17:04:09] DISCONNECTED 88.188.109.57:63144, code: 1009, reason: "Spam", name: ""
[NONE ][17:04:22] DISCONNECTED 88.188.109.57:63142, code: 1001, reason: "", name: ""
[NONE ][17:08:53] CONNECTED    81.228.32.169:62757, origin: "http://agar.io"
[NONE ][17:09:01] CONNECTED    149.154.229.144:27648, origin: "http://agar.io"
[NONE ][17:09:02] DISCONNECTED 149.154.229.144:27648, code: 1009, reason: "Spam", name: ""
[NONE ][17:09:09] CONNECTED    149.154.229.144:27906, origin: "http://agar.io"
[NONE ][17:09:09] DISCONNECTED 149.154.229.144:27906, code: 1009, reason: "Spam", name: ""
[NONE ][17:09:16] CONNECTED    149.154.229.144:25602, origin: "http://agar.io"
[NONE ][17:09:16] DISCONNECTED 149.154.229.144:25602, code: 1009, reason: "Spam", name: ""
[NONE ][17:09:26] CONNECTED    149.154.229.144:25857, origin: "http://agar.io"
[NONE ][17:09:27] DISCONNECTED 149.154.229.144:25857, code: 1009, reason: "Spam", name: ""
[NONE ][17:09:38] CONNECTED    81.228.32.169:62761, origin: "http://agar.io"
[NONE ][17:09:40] CONNECTED    81.228.32.169:62762, origin: "http://agar.io"
[NONE ][17:10:46] >status
[NONE ][17:10:46] Connected players: 14/500
[NONE ][17:10:46] Players: 4 - Bots: 10
[NONE ][17:10:46] Server has been running for 9 minutes
[NONE ][17:10:46] Current memory usage: 10.4/14 mb
[NONE ][17:10:46] Current game mode: Free For All
[NONE ][17:10:46] Current update time: 1.146 [ms]  (perfectly smooth)
[NONE ][17:13:18] CONNECTED    149.154.229.144:25346, origin: "http://agar.io"
[NONE ][17:13:19] DISCONNECTED 149.154.229.144:25346, code: 1009, reason: "Spam", name: ""
[NONE ][17:13:49] DISCONNECTED 81.228.32.169:62541, code: 1000, reason: "Connection timeout", name: ""
[NONE ][17:13:56] CONNECTED    149.154.229.144:28480, origin: "http://agar.io"
[NONE ][17:13:56] DISCONNECTED 149.154.229.144:28480, code: 1009, reason: "Spam", name: ""
[NONE ][17:14:36] DISCONNECTED 81.228.32.169:62757, code: 1000, reason: "Connection timeout", name: ""
[NONE ][17:14:40] DISCONNECTED 81.228.32.169:62761, code: 1000, reason: "Connection timeout", name: ""
[NONE ][17:15:50] DISCONNECTED 81.228.32.169:62762, code: 1000, reason: "Connection timeout", name: ""
[NONE ][17:38:02] CONNECTED    86.184.224.12:55841, origin: "http://agar.io"
[NONE ][17:39:27] DISCONNECTED 86.184.224.12:55841, code: 1001, reason: "", name: ""

**Comment by Jhair2015** [comment] 2017-01-20 17:07
mmmmmmmmmm IP gg

**Comment by ARBCells** [comment] 2017-01-20 17:11
Ehm IP addresses? k. Please help or just stop commenting

**Comment by Jhair2015** [comment] 2017-01-21 00:43
@ARBCells 

°I'll try to help,

°Which host do you use?

°Which version of the server do you use or occupy?

**Comment by ARBCells** [comment] 2017-01-21 16:20
@Jhair2015 I hosting the server with Windows Server 2012 R2. I keep getting this Schannel error in logs: A fatal alert was generated and sent to the remote endpoint. This may result in termination of the connection. The TLS protocol defined fatal error code is 10. The Windows SChannel error state is 1203.

**Comment by Luka967** [comment] 2017-01-22 17:46
@ARBCells It seems like you have TLS on. Try turning off TLS on the server.

**Comment by ARBCells** [comment] 2017-01-22 17:58
@Luka967 Today the server worked 72 minutes before the connection was lost, sometimes it lose connection after only 12-30 minutes.. Weird. Maybe  it is as you say, that the TLS haunts.. How can i turn it off in Windows Server 2012?

**Comment by Luka967** [comment] 2017-01-22 19:38
@ARBCells No idea, ask someone else, I just know that MultiOgar supports it.

**Comment by ARBCells** [comment] 2017-01-23 11:28
Can someone trustworthy go into my server and check everything?

**Comment by ARBCells** [comment] 2017-01-23 13:12
Hi.

You just need to Send the json packages.

:ARB Cells

söndag 22 januari 2017 skrev Luka967 <notifications@github.com>:

**Comment by ARBCells** [comment] 2017-01-23 13:58
Ok this shit going crazy... The server worked for whole 190 minutes before the connection was interrupted. What happen?

**Comment by duwayy** [comment] 2017-01-23 16:18
I got the same problem with latest version of multiogar edited.... Moneyclip sucks

**Comment by patrick0888** [comment] 2017-01-23 21:26
I got the same problem with latest version..

**Comment by Megabyte918** [comment] 2017-01-24 02:01
Refer to #406

**Closed by Megabyte918** 2017-01-24 02:01 UTC
