### ISSUE TITLE
automatic restart?

### ISSUE THREAD

**Issue by kekko9994** [Megabyte918/MultiOgar-Edited#866] opened 2017-05-23 19:18 UTC
Can I add the automatic restart in gameserver.ini?
Please

**Comment by suprix** [comment] 2017-05-23 20:18
Duplicate #684

**Comment by freaky767** [comment] 2017-05-23 20:33
^ close issue

**Comment by AlexHGaming** [comment] 2017-05-23 21:16
Do you not understand how many issues asked this?

**Comment by AlexHGaming** [comment] 2017-05-23 21:20
Duplicate of:
#141 #146 #266 #447 #458 #811 #596 #527 #728 #76 #684 #243

**Comment by AlexHGaming** [comment] 2017-05-23 21:50
@Megabyte918

**Closed** 2017-05-24 00:26 UTC
