### ISSUE TITLE
is it Possible?

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#863] opened 2017-05-21 14:41 UTC
is there a way to eat my w after some seconds but other cell can eat it instantly?

**Comment by AlexHGaming** [comment] 2017-05-21 15:47
??

**Comment by Luka967** [comment] 2017-05-21 18:14
If you eject a cell into the border, you'd immediately eat it. That won't happen in vanilla.
He wants the vanilla mode.

**Comment by Gigabyte918** [comment] 2017-05-22 13:48
yes i want that

**Comment by Megabyte918** [comment] 2017-05-24 01:38
Duplicate of #103 and #317.
And yes there is, but it would reduce performance with ejected mass.

**Closed by Megabyte918** 2017-05-24 01:38 UTC
