### ISSUE TITLE
ADD GOTA.IO SPLITS

### ISSUE THREAD

**Issue by Steve7914** [Megabyte918/MultiOgar-Edited#549] opened 2017-02-13 20:19 UTC
pls

**Comment by AlexHGaming** [comment] 2017-02-13 20:25
Duplicate of #330 and kinda #300 
Please review other issues before making one.

**Comment by Tyler3D** [comment] 2017-02-13 20:33
Yay, that saves me hours of playing gota.io in order to implement it into my fork. xD

**Comment by Jhair2015** [comment] 2017-02-13 20:47
@Tyler3D xDDD

**Comment by Luka967** [comment] 2017-02-13 20:48
@Megabyte918 Close

**Comment by MartincoderMlg** [comment] 2017-02-13 20:58
make this splitVelocity = 100 here u got gota.io lol

**Comment by Luka967** [comment] 2017-02-13 20:59
XD

**Comment by Jhair2015** [comment] 2017-02-13 21:34
@MartincoderMlg wow xDD

**Closed** 2017-02-13 22:51 UTC
