### ISSUE TITLE
How To Auto Restart?

### ISSUE THREAD

**Issue by TheBeast2000** [Megabyte918/MultiOgar-Edited#527] opened 2017-02-10 21:25 UTC
Help me please

**Comment by AlexHGaming** [comment] 2017-02-10 22:16
What type of auto-restart do you mean? Do you mean auto-restarting after someone reaches a certain amount of mass or auto-restarting after a certain time limit?

**Comment by MastaCoder** [comment] 2017-02-10 22:22
Duplicate.

**Comment by TheBeast2000** [comment] 2017-02-10 22:32
After someone reaches a certain amount of mass

**Comment by Luka967** [comment] 2017-02-10 22:36
Duplicate of #447

**Comment by TheBeast2000** [comment] 2017-02-10 22:41
If I put the maximum mass in 5000, and someone reaches that mass, will all players all players die?

**Comment by Luka967** [comment] 2017-02-10 22:50
No

**Comment by TheBeast2000** [comment] 2017-02-10 22:51
And how do I make all players die?

**Comment by FantasyIsBae** [comment] 2017-02-10 23:45
type in killall in the console .

**Comment by Luka967** [comment] 2017-02-11 00:05
xD

**Comment by Jhair2015** [comment] 2017-02-11 00:23
buhh xD

**Closed** 2017-02-11 01:29 UTC
