### ISSUE TITLE
Please help me !

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#116] opened 2016-11-29 10:58 UTC
Hello developers , i have a Big server ( with food of 100 points )

And i cant eat this big food when i am smaller than this , how to modify this?

Thanks much

**Comment by Megabyte918** [comment] 2016-11-29 20:20
Duplicate of #31, #57, #87, #99.

**Closed by Megabyte918** 2016-11-29 20:20 UTC
