### ISSUE TITLE
is possible¿

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#393] opened 2017-01-11 18:47 UTC
is possible spawn like dual-agar? thx

**Comment by ZfsrGhS953** [comment] 2017-01-11 19:00
Duplicate of #294.

**Comment by MastaCoder** [comment] 2017-01-11 22:22
this would require client mods as well.

**Comment by Megabyte918** [comment] 2017-01-12 02:08
@RelTakeover Yes it is, and @MastaCoder and @ZfsrGhS953 are correct.

**Closed by Megabyte918** 2017-01-12 02:08 UTC
