### ISSUE TITLE
Skin issue

### ISSUE THREAD

**Issue by ARBCells** [Megabyte918/MultiOgar-Edited#360] opened 2017-01-06 15:44 UTC
We have created an extension that works as Raga.pw (Multiogar Edited)

The problem we are experiencing is that the skin is only shown to the player, others can not see your skin and you can not see theirs (but as I noticed you can see your own). 

You can test the extension by downloading here: https://goo.gl/RszLTM

1. How did Raga.pw fix this issue? 
2. Someone kind person who can help us solve this?

Thanks in advance,
Joseph

**Comment by Jhair2015** [comment] 2017-01-06 15:55
@ARBCells  Great :) I'll prove it :)

**Comment by ARBCells** [comment] 2017-01-06 17:15
@Jhair2015 Ehm... What are you going to prove?

**Comment by Jhair2015** [comment] 2017-01-06 17:16
@ARBCells  ur Extension

**Comment by AlexHGaming** [comment] 2017-01-06 19:17
There are way too many problems with your extension.

**Comment by Megabyte918** [comment] 2017-01-06 20:14
@ARBCells The problem is either client sided or with your extension, this issue has nothing to do with the development MultiOgar-Edited, so I am closing

**Closed by Megabyte918** 2017-01-06 20:14 UTC

**Comment by kareemman00** [comment] 2017-01-06 21:27
but for now the orignal multi ogar is work ur is not is u in past edited the skins thing in ur server ?? @Megabyte918

**Comment by Megabyte918** [comment] 2017-01-06 21:40
@kareemman00 The only thing I have edited in this fork regarding skins is adding random skins and a custom skins script.

**Comment by kareemman00** [comment] 2017-01-06 22:05
Then Why The F*Ck @megabyte918 i hope u can help me :smiley:

**Comment by ARBCells** [comment] 2017-01-06 22:51
@AlexHGaming What problems do you mean? Except the skin issue.

**Comment by AlexHGaming** [comment] 2017-01-07 09:13
@ARBCells 
I can't connect to my private server when that extension is active.

**Comment by Jhair2015** [comment] 2017-01-07 20:50
@AlexHGaming They are too selfish, they only do it for their own server, I really want to see my skin again :(
