### ISSUE TITLE
IDEA FOR MINIONS

### ISSUE THREAD

**Issue by t11tanYT** [Megabyte918/MultiOgar-Edited#20] opened 2016-11-07 11:12 UTC
1: PULLET MODE (bots collect pullets)
2: stop move bots (stop move for bots)
3: invert bots (like www.raga.pw)
4: time for bots connect (new setting) (no all bots in 1 second)
5: disconnecting bots (new setting) (for more realistic)
6: mass for bots (i can give for friend 10 mass bots and for me 43 mass bots)
7:unlimited names for minions (like bots)
8:random mass bots (new setting) (for more realistic)
all ideas for minions

**Comment by Fantasy-Agario** [comment] 2016-11-07 16:18
So i saw your ideas and i think they're pretty good here's the response (s)

1: Pellet Mode is not a bad idea , but we need to finish fixing bugs first :)
2: Stop Move is pretty hard to make as the agario client only supports Q as a key to switch controls n shit
3:  Define 'Invert Bots'
4: A time for bots to connect would be easy to implement , also it would reduce lag :)
5: Define 'Disconnecting bots'
6: Mass bots will be a feature once we fix bugs
7: Define 'Unlimited Names For Minions'
8: Random Mass Is Definitely a good feature I'll think about it in the future :D 


I'll add some of these to the TODO list

**Comment by AlexandriteErikParacelsus** [comment] 2016-11-08 00:08
@Fantasy-Agario 
3: Probably switch bot mode to into cell and into mouse
5: Probably he means by when remove the minion, the minions would stop following us and stay afk (like a disconnected person)
7: He wants unlimited characters for minion's name

**Comment by Megabyte918** [comment] 2016-11-08 01:44
> 2: stop move bots (stop move for bots)

@t11tanYT added, along with support for E and R keys. press T to freeze minions (only works on clients that support the T key)

**Comment by Fantasy-Agario** [comment] 2016-11-08 22:52
@AlexandriteErikParacelsus Oh ok 

So @t11tanYT 

If the bots stoped after following the player it would cause lag , 

I think u can have unlimited characters (Look in the Gameserver.js file)

**Comment by Megabyte918** [comment] 2016-11-09 03:05
1.) #8
2.) added.
3.) whats the point when they can follow the mouse?
4.) why? whats the point?
5.) Change [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/ai/MinionPlayer.js#L31) line in /ai/MinionPlayer.js to `this.frozen = true;`
6.) What Fantasy said
7.) you can already have unlimited characters by setting their name with the command.
8.) What Fantasy said

**Comment by NameYT** [comment] 2016-11-10 09:11
@Megabyte918 add </random> skins for bots and for minion that would be great :)

**Comment by Megabyte918** [comment] 2016-11-10 20:22
@NameYT You can do this by adding skin names before names in BotNames.txt, but if you want you can use [this](http://pastebin.com/dPtAMVWP) BotNames.txt file that me and a friend made (some of the names in there might be outdated and same with skins), and as for minions you can just set the skin when you set their name. Or if you want minions to have skinnames on by default you can change their default name [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/modules/CommandList.js#L107).

**Comment by NameYT** [comment] 2016-11-11 10:32
@Megabyte918 </random> like that? i want all of the skins the Original skins it only can be seen by the user right

**Comment by Megabyte918** [comment] 2016-11-11 20:13
what

**Comment by systemroot** [comment] 2016-11-11 20:28
@Megabyte918 
what if i wrote 
```
  g.minionName = "minion";
  g.minionName = "minion1";
  g.minionName = "minion3";
etc
```
?

**Comment by Megabyte918** [comment] 2016-11-11 22:31
@systemroot What are you trying to do there? Make them have random names upon spawn? That will not work. If your looking for minions to have random names you can do something like this in BotLoader.js under the `addMinion` function:
<pre>
// Sets random names based on whats in the "minionNames" variable
var minionNames = ["minion", "minion1", "minion2", "minion3"];
var nameIndex = (Math.random() * minionNames.length) >>> 0;
var randomName = minionNames[nameIndex];

// Add to world & set name
s.packetHandler.setNickname(randomName);
</pre>

**Comment by NameYT** [comment] 2016-11-11 23:21
@Megabyte918 just add </random> so the user will not get a hard time :p

**Comment by NameYT** [comment] 2016-11-11 23:27
@Megabyte918 < /random >

**Comment by systemroot** [comment] 2016-11-12 00:39
@Megabyte918 Thank you ^_^

**Comment by NameYT** [comment] 2016-11-12 00:57
@systemroot how did it work for you?

**Comment by Megabyte918** [comment] 2016-11-19 02:58
@t11tanYT All added except for the ones that I have questioned, and Pellet mode which is a duplicate of an existing issue, so I will close for now.

**Closed by Megabyte918** 2016-11-19 02:58 UTC
Labels: enhancement
